### ISSUE TITLE
if routeId or blockId contains dots(.) or colons(:)the detail do not display on the activeBlocks page.

### ISSUE THREAD

**Issue by scrudden** [Transitime/core#10]
$(#routeId-99-11-r11-1 #blockId-68.TA.99-11-r11-1.2.O #block) does not evaluate properly. The . means something to jQuery.

**Comment by skibu** [comment]
Should now be fixed. Please try out the new code.

**Comment by scrudden** [comment]
I had fixed locally and was going to submit a pull request. Next time I'll say if I am going to fix when logging.
Cheers,

Sean.
