### ISSUE TITLE
PredictionAccuracyModule fails to start

### ISSUE THREAD

**Issue by scrudden** [Transitime/core#11]
See log

```
core.log:15:03:46.734 INFO  thread=main [o.t.a.Core:404] Starting up optional module org.transitime.core.predAccuracy.PredictionAccuracyModule
core.log:15:03:46.756 ERROR thread=main [o.t.m.Module:120] Could not run module org.transitime.core.predAccuracy.PredictionAccuracyModule
core.log:java.lang.NoSuchMethodException: org.transitime.core.predAccuracy.PredictionAccuracyModule.<init>(java.lang.String)
```

Perhaps this constructor should be public instead of protected?

```
protected PredictionAccuracyModule(String agencyId)
```

**Comment by scrudden** [comment]
I will change and try out.

**Comment by scrudden** [comment]
This change worked. Will create a pull request.

**Comment by skibu** [comment]
Yes. Change is a the right thing to do. I had only used prediction accuracy module subclasses previously, such as MbtaPredictionAccuracyModule. But you should be able to use PredictionAccuracyModule directly.

**Comment by skibu** [comment]
I needed to make this change for another agency so went ahead and did so. Therefore closing this item.
