### ISSUE TITLE
ERROR: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by scrudden** [Transitime/core#23]
Whenever I get a database jdbc error/exception all subsequent calls to the database result in a

"ERROR: current transaction is aborted, commands ignored until end of transaction block"

For example I got an exception on writing a MonitoringEvent where the message length was greater than 512 characters, which then results in the above error when writing subsequent AVL reports to the database.

I think this is specific to Postgres.

**Comment by skibu** [comment]
I tried this out with the changed code and could not cause the problem to occur anymore. Both MonitoringEvent was fixed to handle really long messages, plus DataDbLogger was fixed to rollback transactions if there is an exception.
