### ISSUE TITLE
GtfsFileProcessor.java needs containsid in fare_rules.txt, should be optional

### ISSUE THREAD

**Issue by Egan109** [Transitime/core#32]
When trying to run GtfsFileProcessor.java, the program would terminate with an error when trying to read into the database the values in the column containsid from fare_rules.txt.

 G07:47:30.912 WARN  [o.h.e.j.s.SqlExceptionHelper:144] SQL Error: 0, SQLState: 23502
07:47:30.912 ERROR [o.h.e.j.s.SqlExceptionHelper:146] ERROR: null value in column "containsid" violates not-null constraint
  Detail: Failing row contains (233, , a, , null, 1).
07:47:30.919 ERROR [o.t.g.DbWriter:204] Error writing GTFS configuration data to db.
org.hibernate.exception.ConstraintViolationException: could not execute statement
    at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129) ~[hibernate-core-4.3.9.Final.jar:4.3.9.Final]
    at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
.
.
.

```
... 15 common frames omitted
```

07:47:30.920 ERROR [o.t.a.GtfsFileProcessor:644] could not execute statement

i temporally  resolved the error by filling in numbers for the containsid.
but containsid is an optional data entry and shouldn't cause an error when empty

orginal file which caused error
[fare_rules.txt](https://github.com/Transitime/core/files/293884/fare_rules.txt)

changed file that fixed error
[fare_rules.txt](https://github.com/Transitime/core/files/293894/fare_rules.txt)

**Comment by skibu** [comment]
You are correct. System wasn't handling situation where contains_id was not
set in GTFS. I checked in updated version of code.

**Comment by skibu** [comment]
Closing issue since fix checked in.
