### ISSUE TITLE
gtfsFileProcessor looks for timeZone from first Agency in database which fails on first run.

### ISSUE THREAD

**Issue by scrudden** [Transitime/core#7]
The constructors

public ServiceUtils(DbConfig dbConfig) 
public Time(DbConfig dbConfig)

call

this.calendar = new GregorianCalendar(dbConfig.getFirstAgency().getTimeZone()); 

Both throw exceptions if no agency in database.

Could catch exception and use GregorianCalendar() for first run?

@skibu Will I implement this fix in a branch?

**Comment by skibu** [comment]
With the latest code I tried creating a new agency database and processed the GTFS data using gtfsFileProcessor. It seemed to work just fine without an exception. I did make changes in the last few days to deal with this problem and other timezone issues. Have you tried it with the latest code?

**Comment by scrudden** [comment]
I will try out in the next few days.

**Comment by scrudden** [comment]
I have since tried this and it is no longer an issue.
